In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\user\\salarys.csv")
print(df)

    Name   Age Salary Department       City
0    Anu    21  25000        CSE   Banglore
1   Ravi    22   None        ECE     Mysore
2  Priya  None  30000        CSE      Hubli
3  Kiran    23  28000       None  Bangalore
4  Meena    21   None        ISE     Mysore
5  Arjun  None  32000        ECE     Mysore

In [3]:
pf = pd.DataFrame(df)

In [10]:
pf

    Name   Age   Salary Department       City
0    Anu    21  25000.0        CSE   Banglore
1   Ravi    22  29000.0        ECE     Mysore
2  Priya  None  30000.0        CSE      Hubli
3  Kiran    23  28000.0       None  Bangalore
4  Meena    21  29000.0        ISE     Mysore
5  Arjun  None  32000.0        ECE     Mysore

In [5]:
pf['Salary'] = pd.to_numeric(pf['Salary'], errors='coerce')

In [7]:
pf['Salary'] = pf['Salary'].fillna(pf['Salary'].median())
print(pf)

    Name   Age   Salary Department       City
0    Anu    21  25000.0        CSE   Banglore
1   Ravi    22  29000.0        ECE     Mysore
2  Priya  None  30000.0        CSE      Hubli
3  Kiran    23  28000.0       None  Bangalore
4  Meena    21  29000.0        ISE     Mysore
5  Arjun  None  32000.0        ECE     Mysore

In [9]:
pf['Department'] = pf['Department'].ffill()
print(pf)

    Name   Age   Salary Department       City
0    Anu    21  25000.0        CSE   Banglore
1   Ravi    22  29000.0        ECE     Mysore
2  Priya  None  30000.0        CSE      Hubli
3  Kiran    23  28000.0       None  Bangalore
4  Meena    21  29000.0        ISE     Mysore
5  Arjun  None  32000.0        ECE     Mysore

In [19]:
pf['Age'] = pf['Age'].ffill()
print(pf)

    Name   Age   Salary  Department       City
0    Anu  21.0  25000.0         NaN   Banglore
1   Ravi  22.0  29000.0         NaN     Mysore
2  Priya  22.0  30000.0         NaN      Hubli
3  Kiran  23.0  28000.0         NaN  Bangalore
4  Meena  21.0  29000.0         NaN     Mysore
5  Arjun  21.0  32000.0         NaN     Mysore

In [13]:
import sys
print(sys.version)

3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]

In [17]:
pf['Age'] = pd.to_numeric(pf['Age'], errors='coerce')

In [18]:
pf

    Name   Age   Salary  Department       City
0    Anu  21.0  25000.0         NaN   Banglore
1   Ravi  22.0  29000.0         NaN     Mysore
2  Priya   NaN  30000.0         NaN      Hubli
3  Kiran  23.0  28000.0         NaN  Bangalore
4  Meena  21.0  29000.0         NaN     Mysore
5  Arjun   NaN  32000.0         NaN     Mysore